# Niels Clayton 300437590

## Question 1
Compute the sum of vector $x$ using a for loop:

$s_{1}=\displaystyle\sum_{i=1}^{5} x_{i}$

In [19]:
x = [0.1, 1.3, -1.5, 0, 12.3]
s1 = 0
for i in x:
    s1 += i
print("s1 = {}".format(s1))

s1 = 12.200000000000001


Compute the sum of vector $x^i$ using a for loop:

$s_{2}=\displaystyle\sum_{i=1}^{5} x_{i}^{i}$

In [20]:
s2 = 0

for i in range(5):
    s2 += (x[i]**i)
print("s2 = {}".format(s2))

s2 = 22893.214100000005


Find the max value of vector $x$ using a for loop:

$M = max\{|x_{i}|, 1, 2, ..., 5\}$

In [21]:
max = float('-inf')

for i in x:
    if (abs(i) > max):
        max = abs(i)
        
print("M = {}".format(max))

M = 12.3


Find the min value of vector $x$ using a for loop:
 
$m = min\{|x_{i}|, 1, 2, ..., 5\}$


In [22]:
min = float('inf')

for i in x:
    if (abs(i) < min):
        min = abs(i)
        
print("m = {}".format(min))

m = 0


Compute the sum, max, and min of vector $x$ using built in python functions:

In [2]:
print("sum calculated function = {}".format(sum(x)))
print("max calculated function = {}".format(max(map(abs,x))))
print("min calculated function = {}".format(min(map(abs,x))))

sum calculated function = 12.200000000000001
max calculated function = 12.3
min calculated function = 0


It can be seen that when we calculate the sum, max, or min using the built in python functions, we get the exact same 
values as we would when calculating them manually with loops. 

## Question 2


In [18]:
import numpy as np

x = np.linspace(2,3,5)                       # Vector of 5 equally spaces values between 2 and 3
x[1] += 1                                    # Add 1 to element 2 of x
y = np.array([4,6,8,10,12])                  # Create array y with successive even values starting at 4
A = np.array([x, np.array([0,0,0,0,0]) , y]) # Form into a matrix
z = []
for i in range(5):
    average = (A[0,i] + A[1,i] + A[2, i])/3  # Average the columns and append them to z
    z.append(average)
np.asarray(z)
print("vector x = {}\n".format(x))
print("vector y = {}\n".format(y))
print("matrix A = \n{}\n".format(A))
print("vector z = {}\n".format(z))


vector x = [2.   3.25 2.5  2.75 3.  ]

vector y = [ 4  6  8 10 12]

matrix A = 
[[ 2.    3.25  2.5   2.75  3.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 4.    6.    8.   10.   12.  ]]

vector z = [2.0, 3.0833333333333335, 3.5, 4.25, 5.0]



## Question 3

Compute $C_1 = A+B$ and $C_2 = A-B$

In [17]:
A = np.matrix([[1,2], [4,-1]])      # Declare matrix A and B
B = np.matrix([[4,-2], [-6, 3]])
c_1 = A+B
print("matrix C_1: \n{}\n".format(c_1))
c_2 = A-B
print("matrix C_2: \n{}\n".format(c_2))


matrix C_1: 
[[ 5  0]
 [-2  2]]

matrix C_2: 
[[-3  4]
 [10 -4]]

matrix D_1: 
[[ -8   4]
 [ 22 -11]]

matrix D_2: 
[[ -4  10]
 [  6 -15]]



Compute $F_{ij} = B_{ij}+A_{ij}B_{ij}^\frac{1}{3}$


In [17]:
F = np.matrix([[]])
temp_row = []
for i in range (2):
    for j in range (2):
        val = (B[i,j]+(A[i,j]*(B[i,j]** 1/3)))
        print(val)
        temp_row.append(val)



5.333333333333333
-3.333333333333333
-14.0
2.0
